# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect - MUST be last redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect for SPA (MUST be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200